version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: addis_mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

    ports:
      - "${DB_PORT}:3307"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: addis_backend
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mysql
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  mysql_data:
