name: Deploy to cPanel via FTP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install and Build
        run: |
          npm ci
          npx prisma generate
          npm run build
          # Create tmp directory for restart trigger
          mkdir -p tmp
          echo "restart-$(date +%s)" > tmp/restart.txt

      - name: Debug - Verify build output
        run: |
          echo "=== Checking build output ==="
          ls -la dist/ || echo "Dist directory not found"

      - name: Deploy build files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.CPANEL_FTP_SERVER }}
          username: ${{ secrets.CPANEL_FTP_USERNAME }}
          password: ${{ secrets.CPANEL_FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./dist/ # Use relative path from FTP root
          exclude: |
            **/node_modules/**
            **/.git*
            **/.github/*

      - name: Trigger restart via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.CPANEL_FTP_SERVER }}
          username: ${{ secrets.CPANEL_FTP_USERNAME }}
          password: ${{ secrets.CPANEL_FTP_PASSWORD }}
          local-dir: ./tmp/
          server-dir: ./tmp/ # Use relative path from FTP root
